### ISSUE TITLE
2v2/3v3 map support possible?

### ISSUE THREAD

**Issue by timmeh2000** [Kelzorz/PeepMode#21]
took me a while to find this as it doesn't seem peep mode is supported anymore... but if there's a way to do 2v2/3v3 maps in a similar way I know it would be adopted well... hope it can be done as it would be a nice option when 10+ ppl in a peep group

**Comment by Kelzorz** [comment]
Some 2v2 maps are already supported, look up Heavy Artillery LE on the arcade.

![image](https://user-images.githubusercontent.com/43789359/81476510-e9849d80-91d7-11ea-852d-84c150003292.png)
