### ISSUE TITLE
Port 2021 season 2 maps

### ISSUE THREAD

**Issue by CluEleSsUK** [Kelzorz/PeepMode#25]
Blizzard have added the following new maps to the ladder pool:
[2000 Atmospheres LE](https://liquipedia.net/starcraft2/2000_Atmospheres_LE)
[Beckett Industries LE](https://liquipedia.net/starcraft2/Beckett_Industries_LE)
[Blackburn LE](https://liquipedia.net/starcraft2/Blackburn_LE)

**Comment by Kelzorz** [comment]
Duplicate card: https://github.com/Kelzorz/PeepMode/issues/20
